require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true

Layout/EndOfLine:
  EnforcedStyle: lf

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/MethodLength:
  Max: 50

Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*'

Lint/UselessAssignment:
  Exclude:
    - '**/spec/**/*'

Style/SignalException:
  Enabled: false

Style/GuardClause:
  Enabled: false
